<a href="https://colab.research.google.com/github/MANDOJU1/pandas/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy(넘파이)
- 과학 계산 및 수학 계산 라이브러리
- 이미지와 컴퓨터 그래픽을 빠르게 처리
- 반복문을 작성하지 않고 전체 데이터 배열을 빠르게 계산할 수 잇는 수학 함수 제공

> NumPy 배열
- 벡(1차원)와 매트릭스(2차원)를 배열이라고 함
- 머신러닝에서 사용하는 주요 데이터 구조

In [1]:
import numpy as np

### 1. 1차원 배열(벡터)

In [3]:
array1 = np.array([1,2,3,4])
array1 # array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
array1.shape # (4,)

(4,)

### 2. 2차원 배열(매트릭스)

In [5]:
data1 = [
    [1,2,3],
    [4,5,6]
]

array2 = np.array(data1)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
array2.shape # (2, 3)

(2, 3)

In [7]:
array3 = np.array([[1,2,3,4]])
array3.shape

(1, 4)

In [8]:
# ndim : 차원 수 알아보기
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


In [9]:
# 파이썬에서 리스트는 서로 다른 타입 가짐

list1 = [1,2,"a",3.5]
list1 # [1, 2, 'a', 3.5]

[1, 2, 'a', 3.5]

In [10]:
# numpy 는 하나의 타입으로 변경해서 array를 생성

np.array(list1)

array(['1', '2', 'a', '3.5'], dtype='<U32')

In [15]:
# array1 의 타입 변경

# array1.dtype # 현재 'int64'
# astype()
# float64 : float 를 64비트로 표현
array_f1 = array1.astype('float64')
array_f1.dtype # 'float64'

dtype('float64')

### 3. NumPy 함수


In [19]:
# arange(n) : 0 ~ n-1 해당하는 넘파이 배열 생성

np.arange(10) # 1 ~ 9
np.arange(5, 10) # 5 ~ 9
np.arange(1, 10, 2) # 1 ~ 9 사이를 2씩 증가

array([1, 3, 5, 7, 9])

In [20]:
# 5의 배수 넘파이 배열 생성

np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [59]:
# zeros(n) : n 개만큼 0을 채워서 넘파이 1 차원 배열 생성
# zeros(행, 열) : 2차원 배열

np.zeros(4) # array([0., 0., 0., 0.])

np.zeros((3,4)) # 3행 4열
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [36]:
# ones(n) : n 개만큼 1을 채워서 넘파이 1 차원 배열 생성

np.ones(4)
np.ones((2,3)) # 2행 3열
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
# np.empty() : 임의의 값을 넣어줌

np.empty(4)
np.empty((3,4), dtype=int)

In [56]:
# np.full() : 특정한 값으로 채워진 넘파이 배열
np.full(4, fill_value=7)
np.full((4,4), fill_value=5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [58]:
# np.eye(n) : 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
# np.linspace(시작, 끝, 전체개수) : 시작과 끝 범위에서 균등하게 분할 된 값으로 반환

np.linspace(1,10,5)
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [63]:
# np.random.rand(n) : 0 ~ 1 사이
np.random.rand(2,3)

array([[0.82895425, 0.82368354, 0.38904306],
       [0.86842552, 0.78684088, 0.93095931]])

In [66]:
# np.random.randn() : 정규분포로 샘플링 된 배열 생성
np.random.randn(5)
np.random.randn(3,4) # (()) : 괄호 두개 X

array([[-0.3811798 ,  2.02600336,  0.95624909, -0.43845318],
       [ 0.48348421,  1.02616821, -1.0062471 ,  0.25329582],
       [-0.97510119, -0.21689058, -0.77766541,  1.48331399]])

In [68]:
# np.random.randnint(시작, 끝, 개수) : 특정 범위안에 숫자 추출

np.random.randint(1, 10, 5)

array([9, 2, 4, 5, 8])

In [76]:
# np.random.seed(임의의 숫자) : random 사용 시 실행할 때마다 결과가 다르게 나오는 것을 방지

np.random.seed(140)
np.random.randn(2,3)

array([[-0.46716782,  0.29599552,  0.18548011],
       [-0.82809842, -0.03192753,  1.00155352]])

In [82]:
# np.random.choice(n) : 0 ~ n-1 까지 임의의 수 추출
np.random.choice(100)
np.random.choice(100, size=(3,4))  # 3행 4열로 만들어줘

array([[36, 36, 40, 13],
       [84, 33, 67, 20],
       [10, 93, 51,  0]])

### 4. 인덱싱과 슬라이싱


In [86]:
arr1 = np.arange(1,10)
arr1

print(arr1[2])
print(arr1[-2])

# 값 바꾸기
arr1[3] = 18
arr1

3
8


array([ 1,  2,  3, 18,  5,  6,  7,  8,  9])

In [89]:
# reshape()
arr1 = np.arange(1,10).reshape(3,3)

In [90]:
print(arr1[0,0])
print(arr1[1,1])

1
5


In [91]:
# 3 차원 : 텐서
arr1 = np.arange(36).reshape(3,4,3)
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [93]:
arr1[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
arr1[0,1]

array([3, 4, 5])

In [97]:
arr1[0,1,-1]

5

In [99]:
# 16 출력
arr1[1,1,1]

16

In [100]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr1[0:3]
arr1[:3]
arr1[3:]

array([], shape=(0, 3), dtype=int64)

In [103]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
arr1[:2, :1]

array([[1],
       [4]])

In [110]:
arr1[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [111]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
arr1[arr1 > 5]

array([6, 7, 8, 9])

### 데이터 형태 변경

In [115]:
y = np.arange(15).reshape(3,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [116]:
# 2차원 배열을 1차원 배열로 만들기 flatten()
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [119]:
# 2행 3열 = 2 * 3 5개

x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [120]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### ndarray 기본 함수
- add(), subtract(), multiply(), divide() 기본함수 제공

In [121]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])

In [122]:
x + y

array([[ 5,  5,  5],
       [10, 10, 10]])

In [123]:
x - y

array([[3, 3, 3],
       [6, 6, 6]])

In [124]:
x * y

array([[ 4,  4,  4],
       [16, 16, 16]])

In [125]:
x / y

array([[4., 4., 4.],
       [4., 4., 4.]])

In [126]:
np.add(x, y)

array([[ 5,  5,  5],
       [10, 10, 10]])

In [127]:
np.subtract(x, y)

array([[3, 3, 3],
       [6, 6, 6]])

In [128]:
np.multiply(x, y)

array([[ 4,  4,  4],
       [16, 16, 16]])

In [129]:
np.divide(x, y)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [142]:
x= np.random.rand(15)
x

array([0.77728353, 0.42874906, 0.37275873, 0.88676377, 0.64922937,
       0.95079259, 0.71284707, 0.51288007, 0.82773245, 0.14276072,
       0.267593  , 0.23751119, 0.72426842, 0.25597802, 0.3711539 ])

In [140]:
x.mean()

0.4560687644171807

In [145]:
# 최대값의 인덱스
x.argmax()

5

In [146]:
x.std()

0.25528967516647144

In [147]:
x.sum()

8.118301875254673

In [148]:
# 이전 요소 덧셈합
x.cumsum()

array([0.77728353, 1.2060326 , 1.57879132, 2.46555509, 3.11478446,
       4.06557705, 4.77842411, 5.29130418, 6.11903663, 6.26179735,
       6.52939035, 6.76690154, 7.49116995, 7.74714797, 8.11830188])